### ISSUE TITLE
Error in solveMDP

### ISSUE THREAD

**Issue by ndslusarz** [sisl/HorizontalCAS#11]
Hello,

While running hCAS and trying to generate tables with `SolveMDP` I had a problem with versions of julia packages (the "n_actions not defined" problem etc.) - I've gone through the other issues similiar to mine, used the fixes from there and found the versions of packages detailed in the open pull request to fix all of those and now I'm getting this error:

`      From worker 2:    20.0% Complete
      From worker 2:    40.0% Complete
      From worker 2:    60.0% Complete
      From worker 2:    80.0% Complete
      From worker 2:    100.0% Complete
      From worker 2:    20.0% Complete
      From worker 2:    40.0% Complete
      From worker 2:    60.0% Complete
      From worker 2:    80.0% Complete
      From worker 2:    100.0% Complete
      From worker 2:    20.0% Complete
      From worker 2:    40.0% Complete
      From worker 2:    60.0% Complete
      From worker 2:    80.0% Complete
      From worker 2:    100.0% Complete
      From worker 2:    20.0% Complete
      From worker 2:    40.0% Complete
      From worker 2:    60.0% Complete
      From worker 2:    80.0% Complete
      From worker 2:    100.0% Complete
      From worker 2:    20.0% Complete
      From worker 2:    40.0% Complete
      From worker 2:    60.0% Complete
      From worker 2:    80.0% Complete
      From worker 2:    100.0% Complete
Warm up: 1/99
ERROR: LoadError: On worker 2:
invalid Array dimensions
Type at .\boot.jl:402 [inlined]
_allocres at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\higherorderfns.jl:229 [inlined]
_noshapecheck_map at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\higherorderfns.jl:160
_shapecheckbc at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\higherorderfns.jl:979 [inlined]
_copy at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\higherorderfns.jl:969 [inlined]
_copy at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\higherorderfns.jl:974 [inlined]
copy at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\higherorderfns.jl:965 [inlined]
materialize at .\broadcast.jl:753 [inlined]
broadcast at .\broadcast.jl:707 [inlined]
* at .\arraymath.jl:52 [inlined]
* at .\operators.jl:502 [inlined]
compute_Qa at E:\HorizontalCAS-master\HorizontalCAS-master\GenerateTable\SolveMDP.jl:70
#109 at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\process_messages.jl:265   
run_work_thunk at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\process_messages.jl:56
run_work_thunk at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\process_messages.jl:65
#102 at .\task.jl:259
Stacktrace:
 [1] #remotecall_fetch#149(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Distributed.Worker, ::Distributed.RRID) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\remotecall.jl:379
 [2] remotecall_fetch(::Function, ::Distributed.Worker, ::Distributed.RRID, ::Vararg{Any,N} where N) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\remotecall.jl:371
 [3] #remotecall_fetch#152 at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\remotecall.jl:406 [inlined]
 [4] remotecall_fetch at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\remotecall.jl:406 [inlined]
 [5] call_on_owner at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\remotecall.jl:479 [inlined]
 [6] fetch(::Future) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Distributed\src\remotecall.jl:511
 [7] computeQ(::Array{Union{MDP, POMDP},1}, ::LocalGIFunctionApproximator{RectangleGrid{6}}, ::Int32, ::Int32) at E:\HorizontalCAS-master\HorizontalCAS-master\GenerateTable\SolveMDP.jl:122
 [8] top-level scope at util.jl:156
 [9] include at .\boot.jl:326 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1038
 [11] include(::Module, ::String) at .\sysimg.jl:29
 [12] exec_options(::Base.JLOptions) at .\client.jl:267
 [13] _start() at .\client.jl:436
in expression starting at E:\HorizontalCAS-master\HorizontalCAS-master\GenerateTable\SolveMDP.jl:140`

While I can see where the error is pointing to I'm not familiar with julia so I haven't found a way to fix it. If you think there is an easy solution I'd be grateful for some help.

Since I have a bit of time pressure on this (I aimed to use the data to run some experiments of my own as well) I was wondering if you maybe had the generated Qtables still saved and could provide those so that I could use them (avoiding having to generate them)? Especially if you don't think there is a simple fix to the issue (I'd have emailed about that but couldn't find the email address).

Thanks!

**Comment by smkatz12** [comment]
Hi @ndslusarz,

I am unable to reproduce this error. Can you print out the dimensions of the variables on that line? (i.e. add some lines above with `println(size(r))`, etc.)?

**Comment by ndslusarz** [comment]
Hi,

I've tried adding a few println lines around the line that causes the issue:

    for i=1:nTau_warm
        @printf("Warm up: %d/%d\n",i,nTau_warm)
        for ai = 1:na
            Q_rc[ai] = remotecall(compute_Qa,mod(ai,nprocs()-1)+2,rews[ai][1],gam,trans[ai],U)
        end
        for ai = 1:na
            println(size(Q))
            println(ai)
            println(Q_rc[ai])
            Q[:,ai] = fetch(Q_rc[ai])
            println("here1")
        end
        U = maximum(Q,dims=2)
    end
    
And the result was:
    
Warm up: 1/99
(268960, 5)
1
Future(2, 1, 43, nothing)
ERROR: LoadError: On worker 2:
invalid Array dimensions

Just to make sure I've run that on a fresh copy of the repo and got the same results. If it's not reproducible I genuinely have no idea what could cause this (the only different thing could be versions of packages but that probably shouldn't be responsible).

**Comment by smkatz12** [comment]
Thanks for adding the print statements. I am still not entirely sure what is causing the issue, but I ran things on my end and stored the output [here](https://drive.google.com/file/d/18YoKeqONPfkS1QTrWTDnk_OQsZsqXAfd/view?usp=sharing). Hope this helps!

**Comment by ndslusarz** [comment]
Thank you for the stored outputs, that solves my problem!
