### ISSUE TITLE
Seemingly uninitialized value

### ISSUE THREAD

**Issue by jia-kai** [sisl/HorizontalCAS#3]
Hi,

The `BitArray` to store the result in `reluValToMmap` is constructed with `BitArray(undef, ...)`, but the values seem not to be initialized. Only certain items are assigned to `true` in the loop. Is this a bug or a deliberate design?

https://github.com/sisl/HorizontalCAS/blob/cd72ffc073240bcd4f0eb9164f441d3ad3fdc074/Reachability/HCAS_Reachability.jl#L578

**Comment by kjulian3** [comment]
I should have explicitly set all values to false immediately after line 578, as was done with the other times BitArray() is used. Thanks for this catch.

**Comment by kjulian3** [comment]
Fixed with bc56a28cfe70b0486b6875deacfda947500bddcb.
