### ISSUE TITLE
Mathematical expressions

### ISSUE THREAD

**Issue by ugurcansoruc** [sisl/HorizontalCAS#6]
I want to ask you a question about HorizontalCAS. I have read the article mentioned on GitHub. But specifically, I couldn't see mathematical expressions on Reward, Transition etc. I wonder what mathematical statement of these codes is spelled and if there is a rule. How can I learn their mathematical statements. Thanks for your answer.

**Comment by mykelk** [comment]
The reward logic is here:
https://github.com/sisl/HorizontalCAS/blob/master/GenerateTable/mdp/rewards.jl

The transition logic is here:
https://github.com/sisl/HorizontalCAS/blob/master/GenerateTable/mdp/transitions.jl
